### ISSUE TITLE
Task0010 - Menu / Correccion de colores del sistema

### ISSUE THREAD

**Issue by LuisTepe** [LuisTepe/PollosMax#28]
Se corregirán los colores del sistema 
Basarse en los colores del prototipo
[https://www.figma.com/file/1yPAYheoYWTXFphGvuvSu7/Prototipo---V2---Iteraci%C3%B3n-1?type=design&node-id=42%3A30&mode=design&t=VnW5o0zW6aAYpZAY-1](url)

**Comment by Ismaeldlr** [comment]
terminado
